#!/usr/bin/env bash

# Requires:
# - gcloud credentials present
# - jq

# OPTIONS:
# GKE_CRED_JSON     gcloud credentials.
# GKE_LOCATION      The AZ the cluster is deployed into.
# GKE_PROJECT       gcloud project.
# RESOURCE_LIST     Resources to remove, as generated by `make find-resources`.
# CLUSTER_SELECTOR  JQ expression for filtering clusters, defaults to all.
# ADDRESS_SELECTOR  JQ expression for filtering addresses, defaults to all.
# DISK_SELECTOR     JQ expression for filtering disks, defaluts to all.
# ACTUALLY_DELETE   Delete will only be executed if this is set to `true`.

. ./defaults.sh
. ../../include/common.sh
# Do not require .envrc

# Check that the reource list is given
if [[ ! -r "${RESOURCE_LIST:-}" ]]; then
    err "Could not read resource list ${RESOURCE_LIST:-(RESOURCE_LIST not set)}"
    exit 1
fi

# check gcloud credentials:
info "Using creds from GKE_CRED_JSON…"
gcloud auth revoke 2>/dev/null || true
gcloud auth activate-service-account --project "${GKE_PROJECT}" --key-file "${GKE_CRED_JSON}"
if [[ $(gcloud auth list  --format="value(account)" | wc -l ) -le 0 ]]; then
    err "GKE_CRED_JSON creds don't authenticate, aborting" && exit 1
fi

if [[ "${ACTUALLY_DELETE:-}" = "true" ]]; then
    PREFIX=""
else
    PREFIX="echo"
    # shellcheck disable=SC2016
    warn 'ACTUALLY_DELETE not set to `true`, doing dry-run'
fi

for cluster in $(jq -r ".clusters[] | select(${CLUSTER_SELECTOR:-true}) | .name" "${RESOURCE_LIST}"); do
    info "Removing cluster ${cluster}"
    ${PREFIX} gcloud container clusters delete "${cluster}" \
        --quiet --project="${GKE_PROJECT}" --zone="${GKE_LOCATION}"
done

for address in $(jq -r ".addresses[] | select(${ADDRESS_SELECTOR:-true}) | .name" "${RESOURCE_LIST}"); do
    info "Removing address ${address}"
    ${PREFIX} gcloud compute addresses delete "${address}" --quiet --region="${GKE_LOCATION%-[abcdef]}"
done

for disk in $(jq -r ".disks[] | select(${DISK_SELECTOR:-true}) | .name" "${RESOURCE_LIST}"); do
    info "Removing disk ${disk}"
    ${PREFIX} gcloud compute disks delete "${disk}" \
        --quiet --project="${GKE_PROJECT}" --zone="${GKE_LOCATION}"
done
