#!/bin/bash

set -Eeuo pipefail

SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

if [ "$1" = get ] && [ "$2" = configmap ]; then
   cat "$SCRIPTPATH"/kubectl_output_get_configmap.json
fi

if [ "$1" = get ] && [ "$2" = nodes ]; then
    cat "$SCRIPTPATH"/kubectl_output_get_nodes.json
fi

if [ "$1" = get ] && [ "$2" = pods ]; then
    cat "$SCRIPTPATH"/kubectl_output_get_pods
fi

exit 0
