.PHONY: devel
devel:
	./build.sh devel http://download.suse.de/ibs/Devel:/CaaSP:/4.0/SLE_15_SP1/

.PHONY: staging
staging:
	./build.sh staging http://download.suse.de/ibs/SUSE:/SLE-15-SP1:/Update:/Products:/CASP40/staging/

.PHONY: product
product:
	./build.sh product http://download.suse.de/ibs/SUSE/Products/SUSE-CAASP/4.0/x86_64/product/

.PHONY: update
update:
	./build.sh update http://download.suse.de/ibs/SUSE/Updates/SUSE-CAASP/4.0/x86_64/update/
