.PHONY: devel
devel:
	./build.sh devel /Devel:/CaaSP:/4.0/SLE_15_SP1/

.PHONY: staging
staging:
	./build.sh staging /SUSE:/SLE-15-SP1:/Update:/Products:/CASP40/staging/

.PHONY: product
product:
	./build.sh product /SUSE/Products/SUSE-CAASP/4.0/x86_64/product/

.PHONY: update
update:
	./build.sh update /SUSE/Updates/SUSE-CAASP/4.0/x86_64/update/
