.PHONY: devel
devel:
	./build.sh devel /Devel:/CaaSP:/4.5/SLE_15_SP2/

.PHONY: staging
staging:
	./build.sh staging /SUSE:/SLE-15-SP2:/Update:/Products:/CASP45/staging/

.PHONY: product
product:
	./build.sh product /SUSE/Products/SUSE-CAASP/4.5/x86_64/product/

.PHONY: update
update:
	./build.sh update /SUSE/Updates/SUSE-CAASP/4.5/x86_64/update/
