# no default goal
# .DEFAULT_GOAL :=

.PHONY: ktw
kwt:
	./kwt.sh

.PHONY: kwt-connect
kwt-connect:
	./kwt_connect.sh

.PHONY: task
task:
	./task.sh

.PHONY: terminal
terminal:
	./terminal.sh

.PHONY: web
web:
	./web.sh

.PHONY: ingress
ingress:
	./ingress.sh

.PHONY: ingress-forward
ingress-forward:
	./ingress_forward.sh

.PHONY: registry
registry:
	./registry.sh

.PHONY: concourse
concourse:
	./concourse.sh

.PHONY: log
log:
	./log.sh

.PHONY: fissile
fissile:
	./fissile.sh

.PHONY: top
top:
	./top.sh