# no default goal
# .DEFAULT_GOAL :=

.PHONY: eirini_release
eirini_release:
	./eirini_release.sh

.PHONY: eirinifs
eirinifs:
	./eirinifs.sh

.PHONY: tf_force_clean
tf_force_clean:
	./tf_force_clean.sh

.PHONY: tf_auto_deploy
tf_auto_deploy:
	./tf_auto_deploy.sh
