#!/usr/bin/env bash

# AKS options
##################

KUBE_VERSION="${KUBE_VERSION:-1.18.2}"

AZURE_RESOURCE_GROUP="${AZURE_RESOURCE_GROUP:-}"
AZURE_APP_ID="${AZURE_APP_ID:-}"
AZURE_PASSWORD="${AZURE_PASSWORD:-}"

AZURE_LOCATION="${AZURE_LOCATION:-westus}"
AZURE_TENANT_ID="${AZURE_TENANT_ID:-}"

AZURE_DNS_JSON="${AZURE_DNS_JSON:-}"
AZURE_DNS_RESOURCE_GROUP="${AZURE_DNS_RESOURCE_GROUP:-susecap-domain}"

AZURE_CLUSTER_NAME="${AZURE_CLUSTER_NAME:-$(whoami)-cap}"
