#!/usr/bin/env bash

# AKS options
##################

KUBECTL_VERSION="${KUBECTL_VERSION:-v1.17.5}"

AZURE_RESOURCE_GROUP="${AZURE_RESOURCE_GROUP:-}"
AZURE_APP_ID="${AZURE_APP_ID:-}"
AZURE_PASSWORD="${AZURE_PASSWORD:-}"

AZURE_LOCATION="${AZURE_LOCATION:-eastus}"
AZURE_TENANT_ID="${AZURE_TENANT_ID:-}"

AZURE_DNS_JSON="${AZURE_DNS_JSON:-}"
AZURE_DNS_RESOURCE_GROUP="${AZURE_DNS_RESOURCE_GROUP:-}"
